### ISSUE TITLE
"Invalid property name/path" with int? type when building an Expression with `The Query Syntax`

### ISSUE THREAD

**Issue by mariomenjr** [alexmurari/Exprelsior#8]
Hey there!
Thanks for making such a useful tool! I discovered it the last month, I have been using it since.

However, I am finding some issues while working with the int? type. 

![image](https://user-images.githubusercontent.com/1946936/94504165-06d4fb00-01bd-11eb-9810-0373e00a442c.png)

According to the documentation, there is no distinction between the properties of different types while creating a query (https://github.com/alexmurari/Exprelsior#elements-syntax), I guess the type is inferred by the generic type given to the `CreateBinaryFromQuery` method.

It is also important to mention that if I use the `CreateBinary` method to create the same expression, it gets created without problems:

![image](https://user-images.githubusercontent.com/1946936/94505016-076e9100-01bf-11eb-9edb-5d54ee4f7085.png)

It's not visible in the image, but the type of the `Po` prop which is member of the class `VwNcrViewLog` is `int?`.

Am I missing something by working with int and `int?` values?

Thanks in advance!

**Comment by alexmurari** [comment]
Hi, @mariomenjr, thanks for reporting this issue and finding this tool useful.

Indeed it's a bug in the query parser regex, currently it only accepts properties with names with at least 3 characters (your property name has 2 characters), hence the regex having trouble to detect it.

I'll be fixing this issue in no time.

**Comment by mariomenjr** [comment]
That was fast! Thanks, @alexmurari :)
